networks:
  mimlnetwork:
    external: true

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - temp_volume:/app/temp
    ports:
      - 8080:8080
    networks:
      - mimlnetwork
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_REDIS_HOST=${REDIS_HOST}
      - SPRING_REDIS_PORT=${REDIS_PORT}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}
      - TEMP_DIR=/app/temp
      - SPRING_GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - SPRING_GRAPH_DB_USERNAME=${GRAPH_DB_USERNAME}
      - SPRING_GRAPH_DB_URL=${GRAPH_DB_URI}
      - SPRING_MONGO_DB_URI=${MONGO_DB_URI}
volumes:
  temp_volume:
